# Generated by Django 6.0.3 on 2026-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('substation_name', models.CharField(max_length=200)),
                ('initial_reading', models.FloatField()),
                ('final_reading', models.FloatField()),
                ('computed_kwh', models.FloatField()),
                ('reading_date', models.DateField()),
            ],
        ),
    ]
