# Generated by Django 6.0.3 on 2026-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyreading',
            name='computed_kwh',
        ),
        migrations.RemoveField(
            model_name='energyreading',
            name='district',
        ),
        migrations.RemoveField(
            model_name='energyreading',
            name='final_reading',
        ),
        migrations.RemoveField(
            model_name='energyreading',
            name='initial_reading',
        ),
        migrations.RemoveField(
            model_name='energyreading',
            name='substation_name',
        ),
        migrations.AddField(
            model_name='energyreading',
            name='energy_mu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='feeder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='feeder_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='final_reading_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='initial_reading_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='mf_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='energyreading',
            name='reading_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
