# Generated by Django 6.0.3 on 2026-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_energyreading_computed_kwh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyreading',
            old_name='final_reading_1',
            new_name='comp_cons',
        ),
        migrations.RenameField(
            model_name='energyreading',
            old_name='initial_reading_1',
            new_name='final_1',
        ),
        migrations.RemoveField(
            model_name='energyreading',
            name='feeder_name',
        ),
        migrations.AddField(
            model_name='energyreading',
            name='feeder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='final_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='initial_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='initial_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energyreading',
            name='mf_2',
            field=models.FloatField(default=0.0),
        ),
    ]
