# Generated by Django 6.0.3 on 2026-04-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_substation_feeder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='mf',
        ),
        migrations.RemoveField(
            model_name='feeder',
            name='type',
        ),
        migrations.AlterField(
            model_name='feeder',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='substation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.discom')),
            ],
        ),
        migrations.AddField(
            model_name='substation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.district'),
        ),
        migrations.CreateModel(
            name='PrivateDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_developers', to='dashboard.discom')),
            ],
        ),
        migrations.AddField(
            model_name='substation',
            name='private_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substations', to='dashboard.privatedeveloper'),
        ),
    ]
