# Generated by Django 6.0.3 on 2026-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_discom_remove_feeder_mf_remove_feeder_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GencoReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_name', models.CharField(max_length=100)),
                ('meter_type', models.CharField(max_length=50)),
                ('mf', models.FloatField()),
                ('opening_reading', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
