-- public.auth_group definition

-- Drop table

-- DROP TABLE public.auth_group;

CREATE TABLE public.auth_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- public.auth_user definition

-- Drop table

-- DROP TABLE public.auth_user;

CREATE TABLE public.auth_user (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	CONSTRAINT auth_user_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_username_key UNIQUE (username)
);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


-- public.dashboard_discom definition

-- Drop table

-- DROP TABLE public.dashboard_discom;

CREATE TABLE public.dashboard_discom (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT dashboard_discom_pkey PRIMARY KEY (id)
);


-- public.dashboard_energyreading definition

-- Drop table

-- DROP TABLE public.dashboard_energyreading;

CREATE TABLE public.dashboard_energyreading (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	reading_date date NOT NULL,
	energy_mu float8 NOT NULL,
	feeder_type varchar(100) NULL,
	comp_cons float8 NOT NULL,
	final_1 float8 NOT NULL,
	mf_1 float8 NOT NULL,
	notes text NULL,
	status varchar(100) NULL,
	feeder varchar(255) NULL,
	final_2 float8 NOT NULL,
	initial_1 float8 NOT NULL,
	initial_2 float8 NOT NULL,
	mf_2 float8 NOT NULL,
	feeder_name varchar(64) NULL,
	meter_type varchar(50) NULL,
	mf int4 NULL,
	opening_reading float4 NULL,
	CONSTRAINT dashboard_energyreading_pkey PRIMARY KEY (id)
);


-- public.dashboard_gencoreadings definition

-- Drop table

-- DROP TABLE public.dashboard_gencoreadings;

CREATE TABLE public.dashboard_gencoreadings (
	feeder_name varchar(100) NOT NULL,
	meter_type varchar(50) NOT NULL,
	mf float8 NOT NULL,
	opening_reading float8 NOT NULL,
	status varchar(20) NOT NULL,
	"FROM-DATE : " varchar(50) NULL,
	"01-01-2026" varchar(64) NULL,
	column3 varchar(50) NULL,
	column4 varchar(50) NULL,
	column5 varchar(50) NULL,
	column6 varchar(50) NULL,
	column7 varchar(50) NULL,
	column8 varchar(50) NULL,
	column9 varchar(50) NULL,
	column10 varchar(50) NULL,
	column11 varchar(50) NULL,
	column12 varchar(50) NULL,
	discom_name varchar(100) NULL,
	"Column A" varchar(64) NULL,
	"Column B" varchar(50) NULL,
	"Column C" varchar(50) NULL,
	"Column D" varchar(50) NULL
);


-- public.discom_abstracts definition

-- Drop table

-- DROP TABLE public.discom_abstracts;

CREATE TABLE public.discom_abstracts (
	abstract_id serial4 NOT NULL,
	discom_name text NOT NULL,
	category text NULL,
	energy_mu_value numeric(15, 4) NULL,
	CONSTRAINT discom_abstracts_pkey PRIMARY KEY (abstract_id)
);


-- public.django_content_type definition

-- Drop table

-- DROP TABLE public.django_content_type;

CREATE TABLE public.django_content_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);


-- public.django_migrations definition

-- Drop table

-- DROP TABLE public.django_migrations;

CREATE TABLE public.django_migrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


-- public.django_session definition

-- Drop table

-- DROP TABLE public.django_session;

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- public.emp_distmap definition

-- Drop table

-- DROP TABLE public.emp_distmap;

CREATE TABLE public.emp_distmap (
	employeeid text NOT NULL,
	username text NOT NULL,
	districtid text NOT NULL,
	active int4 DEFAULT 1 NULL,
	meter_id varchar(100) NULL,
	meter_number varchar(100) NULL,
	substation_id varchar(50) NULL,
	connection_type varchar(20) NULL,
	CONSTRAINT emp_distmap_pkey PRIMARY KEY (employeeid)
);


-- public.genco_meter_readings definition

-- Drop table

-- DROP TABLE public.genco_meter_readings;

CREATE TABLE public.genco_meter_readings (
	reading_id serial4 NOT NULL,
	metering_point_name varchar(255) NOT NULL,
	multiplying_factor numeric(10, 2) DEFAULT 1.0 NULL,
	start_reading numeric(15, 4) NULL,
	end_reading numeric(15, 4) NULL,
	energy_mu numeric(15, 4) GENERATED ALWAYS AS (((end_reading - start_reading) * multiplying_factor)) STORED NULL,
	entry_date timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT genco_meter_readings_pkey PRIMARY KEY (reading_id)
);


-- public.metermaster definition

-- Drop table

-- DROP TABLE public.metermaster;

CREATE TABLE public.metermaster (
	meterid serial4 NOT NULL,
	meterno text NOT NULL,
	status text NULL,
	classid text NULL,
	"type" text NULL,
	createdby text NULL,
	createdts timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	modifiedby text NULL,
	modifiedts timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	remarks text NULL,
	active int4 DEFAULT 1 NULL,
	CONSTRAINT metermaster_meterno_key UNIQUE (meterno),
	CONSTRAINT metermaster_pkey PRIMARY KEY (meterid)
);


-- public.mtdata definition

-- Drop table

-- DROP TABLE public.mtdata;

CREATE TABLE public.mtdata (
	mtid serial4 NOT NULL,
	"date" date NOT NULL,
	mt_json_data text NULL,
	createdby text NULL,
	createdts timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	modifiedby text NULL,
	modifiedts timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	del_ind int4 DEFAULT 0 NULL,
	CONSTRAINT mtdata_pkey PRIMARY KEY (mtid)
);


-- public.ss_master definition

-- Drop table

-- DROP TABLE public.ss_master;

CREATE TABLE public.ss_master (
	substation_id varchar(50) DEFAULT nextval('master_substations_substation_id_seq'::regclass) NOT NULL,
	discom_name text NOT NULL,
	district_name text NOT NULL,
	substation_name text NOT NULL,
	voltage_level text NULL,
	meter_id varchar(100) NULL,
	physical_id varchar(100) NULL,
	make varchar(50) NULL,
	sl_no varchar(50) NULL,
	ctr varchar(20) NULL,
	prev_in_reading numeric DEFAULT 0 NULL,
	curr_in_reading numeric DEFAULT 0 NULL,
	prev_out_reading numeric DEFAULT 0 NULL,
	curr_out_reading numeric DEFAULT 0 NULL,
	mf numeric DEFAULT 1 NULL,
	CONSTRAINT master_substations_pkey PRIMARY KEY (substation_id)
);


-- public.temp_readings definition

-- Drop table

-- DROP TABLE public.temp_readings;

CREATE TABLE public.temp_readings (
	discom_name text NULL,
	district_name text NULL,
	substation_name text NULL,
	voltage_level text NULL,
	mf numeric NULL,
	initial_reading numeric NULL,
	final_reading numeric NULL
);


-- public.temp_readings_load definition

-- Drop table

-- DROP TABLE public.temp_readings_load;

CREATE TABLE public.temp_readings_load (
	col1 text NULL,
	col2 text NULL,
	col3 text NULL,
	col4 text NULL,
	col5 text NULL,
	col6 text NULL,
	col7 text NULL,
	col8 text NULL,
	col9 text NULL,
	col10 text NULL
);


-- public.transmission_loss_log definition

-- Drop table

-- DROP TABLE public.transmission_loss_log;

CREATE TABLE public.transmission_loss_log (
	log_id serial4 NOT NULL,
	total_input_mu numeric(15, 4) NULL,
	total_output_mu numeric(15, 4) NULL,
	loss_mu numeric(15, 4) NULL,
	loss_percentage numeric(5, 2) NULL,
	calculation_date timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT transmission_loss_log_pkey PRIMARY KEY (log_id)
);


-- public.auth_permission definition

-- Drop table

-- DROP TABLE public.auth_permission;

CREATE TABLE public.auth_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- public.auth_user_groups definition

-- Drop table

-- DROP TABLE public.auth_user_groups;

CREATE TABLE public.auth_user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id),
	CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


-- public.auth_user_user_permissions definition

-- Drop table

-- DROP TABLE public.auth_user_user_permissions;

CREATE TABLE public.auth_user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


-- public.dashboard_district definition

-- Drop table

-- DROP TABLE public.dashboard_district;

CREATE TABLE public.dashboard_district (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	discom_id int8 NOT NULL,
	CONSTRAINT dashboard_district_pkey PRIMARY KEY (id),
	CONSTRAINT dashboard_district_discom_id_5dd3702a_fk_dashboard_discom_id FOREIGN KEY (discom_id) REFERENCES public.dashboard_discom(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX dashboard_district_discom_id_5dd3702a ON public.dashboard_district USING btree (discom_id);


-- public.dashboard_privatedeveloper definition

-- Drop table

-- DROP TABLE public.dashboard_privatedeveloper;

CREATE TABLE public.dashboard_privatedeveloper (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	discom_id int8 NOT NULL,
	CONSTRAINT dashboard_privatedeveloper_pkey PRIMARY KEY (id),
	CONSTRAINT dashboard_privatedev_discom_id_fa8d0eb4_fk_dashboard FOREIGN KEY (discom_id) REFERENCES public.dashboard_discom(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX dashboard_privatedeveloper_discom_id_fa8d0eb4 ON public.dashboard_privatedeveloper USING btree (discom_id);


-- public.dashboard_substation definition

-- Drop table

-- DROP TABLE public.dashboard_substation;

CREATE TABLE public.dashboard_substation (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	district_id int8 NULL,
	private_developer_id int8 NULL,
	district varchar(50) NULL,
	"Substation Name" varchar(50) NULL,
	"Feeder Name" varchar(50) NULL,
	CONSTRAINT dashboard_substation_pkey PRIMARY KEY (id),
	CONSTRAINT dashboard_substation_district_id_1afe1f9f_fk_dashboard FOREIGN KEY (district_id) REFERENCES public.dashboard_district(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT dashboard_substation_private_developer_id_18c712c8_fk_dashboard FOREIGN KEY (private_developer_id) REFERENCES public.dashboard_privatedeveloper(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX dashboard_substation_district_id_1afe1f9f ON public.dashboard_substation USING btree (district_id);
CREATE INDEX dashboard_substation_private_developer_id_18c712c8 ON public.dashboard_substation USING btree (private_developer_id);


-- public.district definition

-- Drop table

-- DROP TABLE public.district;

CREATE TABLE public.district (
	district_id varchar(50) NOT NULL,
	substation_id varchar(50) NULL,
	discom_id varchar(50) NULL,
	district_name varchar(100) NULL,
	CONSTRAINT district_pkey PRIMARY KEY (district_id),
	CONSTRAINT fk_substation FOREIGN KEY (substation_id) REFERENCES public.ss_master(substation_id)
);


-- public.django_admin_log definition

-- Drop table

-- DROP TABLE public.django_admin_log;

CREATE TABLE public.django_admin_log (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id int4 NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


-- public.energy_readings definition

-- Drop table

-- DROP TABLE public.energy_readings;

CREATE TABLE public.energy_readings (
	reading_id serial4 NOT NULL,
	substation_id varchar(50) NULL,
	billing_month date NOT NULL,
	mf numeric(10, 2) NULL,
	initial_reading numeric(15, 3) NULL,
	final_reading numeric(15, 3) NULL,
	computed_kwh numeric(18, 3) GENERATED ALWAYS AS (((final_reading - initial_reading) * mf)) STORED NULL,
	entry_date timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT energy_readings_pkey PRIMARY KEY (reading_id),
	CONSTRAINT energy_readings_substation_id_fkey FOREIGN KEY (substation_id) REFERENCES public.ss_master(substation_id)
);


-- public.auth_group_permissions definition

-- Drop table

-- DROP TABLE public.auth_group_permissions;

CREATE TABLE public.auth_group_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


-- public.circle definition

-- Drop table

-- DROP TABLE public.circle;

CREATE TABLE public.circle (
	circle_id varchar(50) NOT NULL,
	circle_name varchar(100) NULL,
	district_id varchar(50) NULL,
	CONSTRAINT circle_pkey PRIMARY KEY (circle_id),
	CONSTRAINT fk_district FOREIGN KEY (district_id) REFERENCES public.district(district_id)
);


-- public.dashboard_feeder definition

-- Drop table

-- DROP TABLE public.dashboard_feeder;

CREATE TABLE public.dashboard_feeder (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	substation_id int8 NOT NULL,
	CONSTRAINT dashboard_feeder_pkey PRIMARY KEY (id),
	CONSTRAINT dashboard_feeder_substation_id_7da39fc5_fk_dashboard FOREIGN KEY (substation_id) REFERENCES public.dashboard_substation(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX dashboard_feeder_substation_id_7da39fc5 ON public.dashboard_feeder USING btree (substation_id);
